### ISSUE TITLE
Huge bug in latest version of wordpress

### ISSUE THREAD

**Issue by kyoukhana** [bainternet/Tax-Meta-Class#121]
When adding new taxonony fields the data is stored in the table wp_termmeta.  Now the issue here is that when trying to retrieve your content it keeps going to the wp_options table which is wrong.  The fix for this is replace **get_tax_meta **function with this code.  This is for the latest version of WordPress 

```
//get term meta field
if (!function_exists('get_tax_meta')){
  function get_tax_meta($term_id,$key,$multi = false){
    global $wpdb;

    $t_id = (is_object($term_id))? $term_id->term_id: $term_id;

    $meta = $wpdb->get_var("SELECT meta_value FROM wp_termmeta where meta_key='".$key."' AND term_id=".$t_id);

    /*Check to see if the string is serialized basically easy check if ther is { not effective way but quick*/
    if (strpos($meta, '{') !== false) {
        $meta = unserialize($meta);
    }

    if (isset($meta)){
      return $meta;
    }else{
      return '';
    }
  }
}

````

**Comment by bainternet** [comment]
You and I have different definitions of "Huge bug".

since WordPress 4.4 there is an api for term meta and is should be used, meaning use native
`*_term_meta` functions instead of this class `*_tax_meta` functions

if you still want to use the "old"  `*_tax_meta` functions you can by simply including the provided 'migration/tax_to_term_meta.php' file which will overwrite the `*_tax_meta` functions to be wrappers for the native `*_term_meta` functions.

also in that file there is a small class called `tax_to_term_meta` which is there to help you migrate your data from options table to term meta.


read the inline documentation of the migration https://github.com/bainternet/Tax-Meta-Class/blob/master/Tax-meta-class%2Fmigration%2Ftax_to_term_meta.php

**Comment by kyoukhana** [comment]
Ah ok was just trying to help.

**Comment by kyoukhana** [comment]
Tried the migration class everything worked like a charm.  Thanks again.

**Comment by bainternet** [comment]
No Problems.
